<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Akka.TestKit.Xunit2" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Gorillas.Actors\Gorillas.Actors.csproj" />
    <ProjectReference Include="..\..\src\Gorillas.Core\Gorillas.Core.csproj" />
    <ProjectReference Include="..\..\src\Gorillas.Data\Gorillas.Data.csproj" />
    <ProjectReference Include="..\..\src\Gorillas.Contracts\Gorillas.Contracts.csproj" />
  </ItemGroup>

</Project>